### ISSUE TITLE
Mod seems to be loading client on server instead of server

### ISSUE THREAD

**Issue by NEXUS2345** [Aurilux/Cybernetica#1]
Crash report: http://pastebin.com/VVBc88pe

**Comment by Aurilux** [comment]
When do you get this crash? When you first start up the server? When you equip the Eye Implant? etc?

**Comment by NEXUS2345** [comment]
On server startup

**Comment by Aurilux** [comment]
Ok, I've located and fixed the issue, but since I neglected to make a branch to work on the new version, it won't be public for a bit. I will close this issue when I release the next update. Thanks for reporting this problem :)
